src/ADO.Web/Controllers/AlunoController.cs
using ADO.Business.Interfaces;
using ADO.Business.Models;
using ADO.Business.Services;
using ADO.Data.Exceptions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADO.Web.Controllers
{
    public class AlunoController : MainController
    {
        private readonly IAlunoRepository _alunoRepository;
        private readonly AlunoService _alunoService;
        public AlunoController(IAlunoRepository alunoRepository,
                               INotificador notificador,
                               AlunoService alunoService) : base(notificador)
        {
            _alunoRepository = alunoRepository;
            _alunoService = alunoService;
        }

        [HttpGet("")]
        [HttpGet("lista-alunos")]
        public async Task<ActionResult> Index()
        {
            var result = await _alunoRepository.ObterTodos();
            return View(result);
        }

        [HttpGet("detalhes-aluno/{id:int}")]
        public async Task<ActionResult> Details(int id)
        {


            if (id <= 0)
            {
                AdicionarErroNotificacao("O Registro não foi informado!");
                return BadRequest();
            }

            var resultboll = await _alunoRepository.ObterBool(id);
            var result = await _alunoRepository.ObterPorId(id);
            return View(result);

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Aluno aluno)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            await _alunoService.Adicionar(aluno);

            if (!OperacaoValida()) return View(aluno);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("editar-aluno/{id:int}")]
        public async Task<ActionResult> Edit(int id)
        {

            var result = await _alunoRepository.ObterPorId(id);
            if (OperacaoValida()) RedirectToAction("Index");

            return View(result);
        }

        [HttpPost("editar-aluno/{id:int}")]
        public async Task<ActionResult> Edit(int id, Aluno aluno)
        {

            if (id != aluno.Id) return BadRequest();

            if (!ModelState.IsValid) return BadRequest();


            var result = await _alunoService.Atualizar(aluno);

            return RedirectToAction("Details", new { result.Id });
        }

        public async Task<ActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();

            var result = await _alunoRepository.ObterPorId(id);

            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (id <= 0) return BadRequest();
            await _alunoService.Excluir(id);
            if (!OperacaoValida())
            {
                return View();
            }

            return RedirectToAction(nameof(Index));


        }


    }
}

src/ADO.Web/Controllers/CategoriaController.cs
using ADO.Business.Interfaces;
using ADO.Business.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADO.Web.Controllers
{
    public class CategoriaController : MainController
    {

        public readonly ICategoriaRepository _categoriaRepository;
        public readonly ICategoriaService _categoriaService;

        public CategoriaController(ICategoriaRepository categoriaRepository,
                                   ICategoriaService categoriaService,
                                   INotificador notificador):base(notificador)
        {
            _categoriaRepository = categoriaRepository;
            _categoriaService = categoriaService;
        }

        public async Task<ActionResult> Index()
        {
            var result = await _categoriaRepository.ObterTodos();
            return View(result);
        }

        public async Task<ActionResult> Details(int id)
        {
            if (id <= 0) return NotFound();

            var result = await _categoriaRepository.ObterPorId(id);

            if (result == null) return NotFound();

            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Categoria categoria)
        {
            if (!ModelState.IsValid) return View(categoria);

            await _categoriaService.Adicionar(categoria);

            if (!OperacaoValida()) return View(categoria);

            return RedirectToAction(nameof(Index));            
        }

        public async Task<ActionResult> Edit(int id)
        {
            var result = await _categoriaRepository.ObterPorId(id);
            if (result == null) return NotFound();
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Categoria categoria)
        {
            if (id != categoria.Id) return View();

            await _categoriaService.Atualizar(categoria);

            if (!OperacaoValida()) return View(categoria);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(int id)
        {
            var result = await _categoriaRepository.ObterPorId(id);
            if (result == null) return NotFound();
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Categoria categoria)
        {
            
            await _categoriaService.Excluir(categoria.Id);
            if (!OperacaoValida()) return View(categoria);
            
            return RedirectToAction(nameof(Index));

        }
    }
}

src/ADO.Web/Controllers/CursosController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ADO.Business.Models;
using ADO.Business.Interfaces;
using System.Collections.Generic;
using System.Linq;

namespace ADO.Web.Controllers
{
    public class CursosController : MainController
    {
        private readonly ICursoRepository _cursoRepository;
        private readonly ICursoService _cursoService;
        private readonly ICategoriaRepository _CategoriaRepository;
        private readonly IAlunoRepository _alunoRepository;

        public CursosController(ICursoRepository cursoRepository,
                                INotificador notificacao,
                                ICursoService cursoService,
                                ICategoriaRepository categoriaRepository,
                                IAlunoRepository alunoRepository)
            : base(notificacao)
        {
            _cursoRepository = cursoRepository;
            _cursoService = cursoService;
            _CategoriaRepository = categoriaRepository;
            _alunoRepository = alunoRepository;
        }


        public async Task<IActionResult> Index()
        {
            var result = await _cursoRepository.ObterTodos();
            return View(result);
        }
        public async Task<IActionResult> ObterAlunosPorCursos()
        {
            var result = await _cursoRepository.ObterAlunosPorCursos();
            return View(result);
        }

        public async Task<IActionResult> Details(int id)
        {
            var curso = await _cursoRepository.ObterPorId(id);

            return View(curso);
        }


        public async Task<IActionResult> Create()
        {
            var curso = new Curso
            {
                Categorias = await ObterCategorias()
            };

            return View(curso);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Curso curso)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            await _cursoService.Adicionar(curso);
            if (!OperacaoValida()) return View(curso);

            return RedirectToAction(nameof(Index));

        }


        public async Task<IActionResult> Edit(int id)
        {
            var curso = await _cursoRepository.ObterPorId(id);
            if (curso == null)
            {
                return BadRequest();
            }
            curso.Categorias = await ObterCategorias();
            return View(curso);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Curso curso)
        {
            if (id != curso.Id)
            {
                AdicionarErroNotificacao("Os Ids não conferem!");
                return View(curso);
            }

            if (!ModelState.IsValid) return BadRequest(ModelState);

            var result = await _cursoService.Atualizar(curso);

            if (!OperacaoValida()) return View(curso);

            return RedirectToAction(nameof(Index));

        }

        // GET: Cursos/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var curso = await _cursoRepository.ObterPorId(id);
            if (curso == null)
            {
                return BadRequest(curso);
            }

            return View(curso);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var curso = await _cursoRepository.ObterPorId(id);
            if (curso == null)
            {
                AdicionarErroNotificacao($"O Curso com o Registro: {id} não foi encontrado");
                return BadRequest();
            }

            await _cursoService.Excluir(id);

            if (!OperacaoValida()) return View(curso);

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> MatricularAlunoCurso()
        {

            var alunocurso = await CarregarAlunosECursos();


            return View(alunocurso);
        }

        [HttpPost()]
        public async Task<IActionResult> MatricularAlunoCurso(AlunoCurso alunoCurso)
        {
            if (!ModelState.IsValid) return BadRequest();

            await _cursoRepository.MatricularAlunoCurso(alunoCurso.Aluno_id, alunoCurso.Curso_Id);

            if (!OperacaoValida())
            {
                alunoCurso = await CarregarAlunosECursos();
                return View(alunoCurso);
            }

            return RedirectToAction("ObterAlunosPorCursos");
        }
        private async Task<IEnumerable<Categoria>> ObterCategorias()
        {
            return await _CategoriaRepository.ObterTodos();
        }

        private async Task<AlunoCurso> CarregarAlunosECursos()
        {
            var Alunos = await _alunoRepository.ObterTodos();
            var Cursos = await _cursoRepository.ObterTodos();
            var alunocurso = new AlunoCurso
            {
                alunos = Alunos.ToList(),
                cursos = Cursos.ToList()
            };
            return alunocurso;
        }
    }
}

src/ADO.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ADO.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ADO.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Aluno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cursos" asp-action="ObterAlunosPorCursos">Turmas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ADO.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>