src/ADO.Web/Controllers/AlunoController.cs
using ADO.Business.Interfaces;
using ADO.Business.Models;
using ADO.Business.Services;
using ADO.Data.Exceptions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADO.Web.Controllers
{
    public class AlunoController : MainController
    {
        private readonly IAlunoRepository _alunoRepository;
        private readonly AlunoService _alunoService;
        public AlunoController(IAlunoRepository alunoRepository,
                               INotificador notificador,
                               AlunoService alunoService) : base(notificador)
        {
            _alunoRepository = alunoRepository;
            _alunoService = alunoService;
        }

        [HttpGet("")]
        [HttpGet("lista-alunos")]
        public async Task<ActionResult> Index()
        {
            var result = await _alunoRepository.ObterTodos();
            return View(result);
        }

        [HttpGet("detalhes-aluno/{id:int}")]
        public async Task<ActionResult> Details(int id)
        {


            if (id <= 0)
            {
                AdicionarErroNotificacao("O Registro não foi informado!");
                return BadRequest();
            }

            var resultboll = await _alunoRepository.ObterBool(id);
            var result = await _alunoRepository.ObterPorId(id);
            return View(result);

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Aluno aluno)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            await _alunoService.Adicionar(aluno);

            if (!OperacaoValida()) return View(aluno);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("editar-aluno/{id:int}")]
        public async Task<ActionResult> Edit(int id)
        {

            var result = await _alunoRepository.ObterPorId(id);
            if (OperacaoValida()) RedirectToAction("Index");

            return View(result);
        }

        [HttpPost("editar-aluno/{id:int}")]
        public async Task<ActionResult> Edit(int id, Aluno aluno)
        {

            if (id != aluno.Id) return BadRequest();

            if (!ModelState.IsValid) return BadRequest();


            var result = await _alunoService.Atualizar(aluno);

            return RedirectToAction("Details", new { result.Id });
        }

        public async Task<ActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();

            var result = await _alunoRepository.ObterPorId(id);

            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (id <= 0) return BadRequest();
            await _alunoService.Excluir(id);
            if (!OperacaoValida())
            {
                return View();
            }

            return RedirectToAction(nameof(Index));


        }


    }
}

src/ADO.Web/Extensions/SummaryViewComponent.cs
using ADO.Business.Interfaces;
using ADO.Business.Notificacoes;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ADO.Web.Extensions
{

    [ViewComponent(Name = "Summary")]
    public class SummaryViewComponent : ViewComponent
    {
     private readonly INotificador _notificador;

        public SummaryViewComponent(INotificador notificador)
        {
           _notificador = notificador;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notificador.ObterNotificacoes());
            notificacoes.ForEach(m => ViewData.ModelState.AddModelError(string.Empty, m.Mensagem));
            return View();
        }


    }
}

src/ADO.Web/Views/Aluno/Create.cshtml
@model ADO.Business.Models.Aluno

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
                        

            <vc:summary></vc:summary>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input type="date" asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>            
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/ADO.Web/Views/Aluno/Delete.cshtml
@model ADO.Business.Models.Aluno

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>
<vc:summary></vc:summary>
<h3>Tem certeza que deseja excluir esse Registro?</h3>
<div>
    <h4>Aluno</h4>
    <hr />
    <vc:summary></vc:summary>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nascimento)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cadastrado_em)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cadastrado_em)
        </dd>
    </dl>

    <form asp-action="delete" asp-route-id="@Model.Id">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/ADO.Web/Views/Aluno/Details.cshtml
@model ADO.Business.Models.Aluno

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cadastrado_em)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cadastrado_em)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

src/ADO.Web/Views/Aluno/Edit.cshtml
@model ADO.Business.Models.Aluno

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <vc:summary></vc:summary>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Cadastrado_em" class="control-label"></label>
                <input reasp-for="Cadastrado_em" class="form-control" />
                <span asp-validation-for="Cadastrado_em" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/ADO.Web/Views/Aluno/Index.cshtml
@model IEnumerable<ADO.Business.Models.Aluno>

@{
    ViewData["Title"] = "Aluno";
}

<h1>Aluno</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nascimento)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Cadastrado_em)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nascimento)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Cadastrado_em)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { item.Id}) |
                @Html.ActionLink("Details", "Details", new { item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { item.Id })
            </td>
        </tr>
}
    </tbody>
</table>